import { Template } from '@pdfme/common'

export const invoiceTemplate: Template = {
  basePdf: {
    width: 210,
    height: 297,
    padding: [20, 20, 20, 20],
  },
  schemas: [
    [
      {
        name: 'invoice_title',
        type: 'text',
        position: { x: 20, y: 20 },
        width: 100,
        height: 15,
        fontSize: 28,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#2563eb',
      },
      {
        name: 'invoice_id',
        type: 'text',
        position: { x: 130, y: 20 },
        width: 60,
        height: 10,
        fontSize: 12,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'right',
        fontColor: '#666666',
      },

      {
        name: 'from_label',
        type: 'text',
        position: { x: 20, y: 45 },
        width: 30,
        height: 8,
        fontSize: 12,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#374151',
      },
      {
        name: 'from_name',
        type: 'text',
        position: { x: 20, y: 55 },
        width: 80,
        height: 10,
        fontSize: 14,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#111827',
      },
      {
        name: 'from_email',
        type: 'text',
        position: { x: 20, y: 67 },
        width: 80,
        height: 8,
        fontSize: 11,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#6b7280',
      },

      {
        name: 'to_label',
        type: 'text',
        position: { x: 20, y: 85 },
        width: 30,
        height: 8,
        fontSize: 12,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#374151',
      },
      {
        name: 'client_name',
        type: 'text',
        position: { x: 20, y: 95 },
        width: 80,
        height: 10,
        fontSize: 14,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#111827',
      },
      {
        name: 'client_email',
        type: 'text',
        position: { x: 20, y: 107 },
        width: 80,
        height: 8,
        fontSize: 11,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#6b7280',
      },
      {
        name: 'client_address',
        type: 'text',
        position: { x: 20, y: 117 },
        width: 80,
        height: 20,
        fontSize: 10,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#6b7280',
      },

      {
        name: 'issue_date_label',
        type: 'text',
        position: { x: 130, y: 45 },
        width: 35,
        height: 8,
        fontSize: 11,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#374151',
      },
      {
        name: 'issue_date',
        type: 'text',
        position: { x: 130, y: 55 },
        width: 60,
        height: 8,
        fontSize: 11,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#111827',
      },
      {
        name: 'due_date_label',
        type: 'text',
        position: { x: 130, y: 70 },
        width: 35,
        height: 8,
        fontSize: 11,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#374151',
      },
      {
        name: 'due_date',
        type: 'text',
        position: { x: 130, y: 80 },
        width: 60,
        height: 8,
        fontSize: 11,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#111827',
      },
      {
        name: 'status_label',
        type: 'text',
        position: { x: 130, y: 95 },
        width: 35,
        height: 8,
        fontSize: 11,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#374151',
      },
      {
        name: 'status',
        type: 'text',
        position: { x: 130, y: 105 },
        width: 60,
        height: 8,
        fontSize: 11,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#16a34a',
      },

      {
        name: 'description_label',
        type: 'text',
        position: { x: 20, y: 150 },
        width: 50,
        height: 8,
        fontSize: 12,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#374151',
      },
      {
        name: 'description',
        type: 'text',
        position: { x: 20, y: 162 },
        width: 170,
        height: 15,
        fontSize: 11,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#111827',
      },

      // Properly configured table following PDFme documentation
      {
        name: 'items_table',
        type: 'table',
        position: { x: 20, y: 180 },
        width: 170,
        height: 60,
        showHead: true,
        head: ['Item', 'Qty', 'Price', 'Total'],
        headWidthPercentages: [40, 20, 20, 20],
        tableStyles: {
          borderWidth: 0.3,
          borderColor: '#000000',
        },
        headStyles: {
          fontName: 'NotoSerifJP-Regular',
          fontSize: 10,
          characterSpacing: 0,
          alignment: 'left',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#ffffff',
          backgroundColor: '#374151',
          borderWidth: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
          },
          padding: {
            top: 3,
            right: 3,
            bottom: 3,
            left: 3,
          },
        },
        bodyStyles: {
          fontName: 'NotoSerifJP-Regular',
          fontSize: 9,
          characterSpacing: 0,
          alignment: 'left',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#000000',
          borderColor: '#888888',
          backgroundColor: '',
          alternateBackgroundColor: '#f9f9f9',
          borderWidth: {
            top: 0.1,
            right: 0.1,
            bottom: 0.1,
            left: 0.1,
          },
          padding: {
            top: 2,
            right: 3,
            bottom: 2,
            left: 3,
          },
        },
        columnStyles: {},
      },

      {
        name: 'total_label',
        type: 'text',
        position: { x: 130, y: 250 },
        width: 35,
        height: 12,
        fontSize: 14,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#374151',
      },
      {
        name: 'total_amount',
        type: 'text',
        position: { x: 130, y: 265 },
        width: 60,
        height: 15,
        fontSize: 18,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'left',
        fontColor: '#111827',
      },

      {
        name: 'footer_note',
        type: 'text',
        position: { x: 20, y: 285 },
        width: 170,
        height: 20,
        fontSize: 9,
        fontName: 'NotoSerifJP-Regular',
        alignment: 'center',
        fontColor: '#9ca3af',
      },
    ],
  ],
}
